# -*- coding: utf-8 -*-
# FIXOS: entram em todo ciclo (fast lane)
ALWAYS_SYMBOLS = [
    "BTCUSDT","ETHUSDT","BNBUSDT","SOLUSDT","XRPUSDT","ADAUSDT"
]

# ROTATIVOS: entram por rotação
ROTATING_SYMBOLS = [
    "DOGEUSDT","MATICUSDT","DOTUSDT","LTCUSDT","LINKUSDT","TRXUSDT","AVAXUSDT","ATOMUSDT","FILUSDT",
    "ARBUSDT","APTUSDT","OPUSDT","NEARUSDT","INJUSDT","RNDRUSDT","SUIUSDT","ETCUSDT","AAVEUSDT",
    "FTMUSDT","GRTUSDT","IMXUSDT","PEPEUSDT","SEIUSDT","TONUSDT","XLMUSDT","BCHUSDT","EGLDUSDT",
    "TIAUSDT","JUPUSDT","PYTHUSDT","WIFUSDT","STRKUSDT","SANDUSDT","MANAUSDT","CHZUSDT","FLOWUSDT",
    "APEUSDT","ARUSDT","HBARUSDT","RUNEUSDT","KASUSDT","FLOKIUSDT","BONKUSDT"
]
